### ISSUE TITLE
Instructions on how to cite

### ISSUE THREAD

**Issue by mikeevmm** [ichuang/pyqsp#2]
Hello,

First of all, thank you for making `pyqsp` public. The Quantum Signal Processing theory is already phenomenal, but, as evidenced by [Chao et al.][1], and as shown by the existance of `pyqsp` in the first place, it would be very complicated to get started in practice without this package.

Per the introduction section of the README, since the package borrows and extends techniques from multiple publications, I would appreciate if there were explicit citation instructions, to reference when using the package in the context of other work.

[1]: https://arxiv.org/abs/2003.02831

**Comment by andrewktan** [comment]
Thanks for your comment! I've included a section in the README regarding citation as well as a [citation file](https://github.com/ichuang/pyqsp/blob/master/CITATION).
